config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#register', as: :register
  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout

  resources :posts, except: [:destroy] do
    resources :comments, only: [:create]
  end
  resources :categories, only: [:new, :show, :create]

  resources :users, only: [:create, :show, :edit, :update]
end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :category
  belongs_to :post
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categorizations
  has_many :posts, through: :categorizations

  validates :name, length: {minimum: 3}, presence: true, uniqueness: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post

  validates :user_id, presence: true
  validates :post_id, presence: true
  validates :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :categorizations
  has_many :categories, through: :categorizations

  validates :title, presence: true, length: {minimum: 1}
  validates :url, presence: true, uniqueness: true
  validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments
  has_secure_password validations: false

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, on: :create, length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :logged_in?, :current_user

  def logged_in?
    !!current_user
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    unless logged_in?
      flash[:error] = 'No Bueno!'
      redirect_to root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user, only: [:new, :create]

  def show
    @category = Category.find(params[:id])
    @posts = @category.posts
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = "New category was created successfully!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def category_params
    params.require(:category).permit!
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user, only: [:create]

  def create
    @comment = Comment.new(comments_params)
    @post = Post.find(params[:post_id])
    @comment.post = @post
    @comment.creator = current_user

    if @comment.save
      flash[:notice] = "Comment created successfully!"
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  private

  def comments_params
    params.require(:comment).permit!
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :update, :edit]
  before_action :require_user, only: [:new, :create]
  before_action :require_same_user, only: [:update, :edit]

  def index
    @posts = Post.all
  end

  def show
    @comment = Comment.new
  end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user

    if @post.save
      flash[:notice] = "New post successfully created!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "Your post was successfully updated!"
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def new
    @post = Post.new
  end

  def edit
  end

  private

  def require_same_user
    unless logged_in? && params[:id] == current_user.id
      flash[:error] = 'No Bueno!'
      redirect_to root_path
    end
  end

  def post_params
    params.require(:post).permit!
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_user, only: [:destroy]

  def new; end

  def create
    user = User.find_by(username: params[:username])
               .try(:authenticate, params[:password])

    if user
      flash[:notice] = "Welcome #{user.username}!"
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = 'There is something wrong with your username or password'
      redirect_to login_path
    end
  end

  def destroy
    user = current_user
    flash[:notice] = "Goodbye #{user.username}"

    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: [:register, :create]

  def register
    @user = User.new
  end

  def create
    @user = User.new(users_params)

    if @user.save
      flash[:notice] = "#{@user.username} was successfully created!"
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render 'register'
    end
  end

  def show
    @posts = @user.posts
    @comments = @user.comments
  end

  def edit
  end

  def update
    if @user.update(users_params)
      flash[:notice] = 'Your profile was updated!'
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def users_params
    params.require(:user).permit(:username, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def fix_url(url)
    return url if /^https?:\/\//.match url

    "http://#{url}"
  end

  def datetime(dt)
    dt.strftime("%b %d, %Y %I:%M %p %Z")
  end

  def same_user?(post)
    current_user == post.creator
  end
end

app/views/categories/new.html.erb
<h3>New Category</h3>

<%= render 'shared/errors', item: @category %>

<div class="span8 well">
  <%= form_for @category do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br />
    <%= f.submit class: 'btn btn-success' %>
  <% end %>
</div>

app/views/categories/show.html.erb
<h3><%= @category.name %></h3>

<%= render 'posts/posts', posts: @posts %>

app/views/comments/_comment.html.erb
<div class="span8 well">
  <p><em>"<%= comment.body %>"</em> on
    <% if show_post %>
      <%= link_to comment.post.title, post_path(comment.post) %>
    <% end %>
  </p>
  <span>
    <p><i>Created by:</i> <%= comment.creator.username %> at <%= comment.created_at %></p>
  </span>
</div>

app/views/comments/_comments.html.erb
<% comments.each do |comment| %>
  <%= render 'comments/comment', comment: comment, show_post: show_post %>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
  <% if logged_in? %>
    <div class="nav_item">
      <%= link_to 'New Post', new_post_path, class: 'btn btn-small btn-success' %>
    </div>

    <div class="btn-group nav_item">
      <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
        <%= current_user.username %> <span class="caret"></span>
      <% end %>
      <ul class="dropdown-menu">
        <li>
          <%= link_to(edit_user_path(current_user)) do %>
            <i class="icon-pencil"></i>
            edit profile
          <% end %>
        </li>
        <li>
          <%= link_to(user_path(current_user)) do %>
            <i class="icon-user"></i>
            view profile
          <% end %>
        </li>
        <li>
          <%= link_to(logout_path) do %>
            <i class="icon-circle-arrow-left"></i>
            logout
          <% end %>
        </li>
      </ul>
    </div>
  <% else %>
    <div class="nav_item">
      <%= link_to 'Register', register_path, class: 'btn btn-small btn-success' %>
    </div>

    <div class="nav_item">
      <%= link_to 'Login', login_path, class: 'btn btn-small' %>
    </div>
  <% end %>
</ul>

<div class="btn-group nav_item">
  <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
    Categories <span class="caret"></span>
  <% end %>
  <ul class="dropdown-menu">
    <% Category.all.each do |category| %>
      <li>
        <%= link_to category.name, category_path(category) %>
      </li>
    <% end %>
    <% if logged_in? %>
      <li class="divider"></li>
      <li>
        <%= link_to(new_category_path) do %>
          <i class="icon-plus"></i>
          New Category
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_categories.html.erb
<% if post.categories.any? %>
  <p>Tags:
    <% post.categories.each do |category| %>
      <%= link_to category.name, category_path(category) %>
    <% end %>
  </p>
<% end %>

app/views/posts/_form.html.erb
<%= render 'shared/errors', item: @post %>

<div class="span8 well">
  <%= form_for @post do |f| %>
    <div class="control-group">
      <%= f.label :title %>
      <%= f.text_field :title %><br>
    </div>

    <div class="control-group">
      <%= f.label :url %>
      <%= f.text_field :url %><br>
    </div>

    <div class="control-group">
      <%= f.label :description %>
      <%= f.text_area :description %><br>
    </div>

    <div class="control-group">
      <%= f.label :categories %>
      <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b| %>
        <%= b.label(class: 'checkbox inline') { b.check_box(class: 'checkbox inline') + b.text } %>
      <% end %>
    </div>


    <%= f.submit class: 'btn btn-success' %>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="span8 well">
  <%= render 'posts/categories', post: post %>
  <h3><%= link_to post.title, fix_url(post.url) %></h3>
  <p><%= post.description %></p>
  <span>
    <p><i>Created by:</i> <%= post.creator.username %> on <%= datetime(post.created_at) %></p>
  </span>
  <br />
  <% if logged_in? && same_user?(post) %>
    <%= link_to 'Edit', edit_post_path(post) %>
    <br />
  <% end %>
  <%= link_to 'Comments', post_path(post) %>
</div>

app/views/posts/_posts.html.erb
<% if posts.any? %>
  <% posts.each do |post| %>
    <%= render 'posts/post', post: post %>
  <% end %>
<% else %>
  <h3>No Posts</h3>
<% end %>

app/views/posts/edit.html.erb
<h3>Edit Post</h3>

<%= render 'form' %>

app/views/posts/index.html.erb
<h3>Welcome!</h3>

<%= render 'posts', posts: @posts %>

app/views/posts/new.html.erb
<h3>New Post</h3>

<%= render 'form' %>

app/views/posts/show.html.erb
<% if logged_in? && same_user?(@post) %>
  <p>
    [<%= link_to 'Edit Post', edit_post_path(@post) %>]
  </p>
<% end %>

<h3><%= @post.title %></h3>

<hr>
<p><%= @post.description %></p>

<br><br>

<% if logged_in? %>

  <%= render 'shared/errors', item: @comment %>

  <div>
    <h5>New Comment</h5>
    <%= form_for [@post, @comment] do |f| %>
      <%= f.label :body, 'Message' %>
      <%= f.text_area :body %>
      <br />
      <%= f.submit %>
    <% end %>
  </div>

  <br>

<% end %>

<h4>Comments:</h4>

<%= render 'comments/comments', comments: @post.comments %>

app/views/shared/_errors.html.erb
<% if item.errors.any? %>
  <div class="row">
    <div class="alert alert-error">
      <h5>Please fix the following errors:</h5>
      <ul>
      <% item.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h3>Edit Profile</h3>

<%= render 'shared/errors', item: @user %>

<div class="well">
  <%= form_for @user do |f| %>
    <div class="control-group">
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>

    <div class="control-group">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>

    <%= f.submit class: 'btn btn-success' %>
  <% end %>
</div>

app/views/users/register.html.erb
<h3>Register New User</h3>

<%= render 'shared/errors', item: @user %>
<div class="well">
  <%= form_for @user do |f| %>
    <div class="control-group">
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>

    <div class="control-group">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>

    <%= f.submit 'Register', class: 'btn btn-success' %>
  <% end %>
</div>

app/views/users/show.html.erb
<h3>Profile: <%= @user.username %></h3>

<hr>

<div class="well">
  <dl class="dl-horizontal">
    <dt>Username:</dt>
    <dd><%= @user.username %></dd>
  </dl>
</div>

<br>


<h5><%= @user.username %>'s Activity</h5>

<ul class="nav nav-tabs">
  <li class="<%= 'active' unless params[:tab] == 'comments' %>">
    <%= link_to "Posts (#{@posts.size})", user_path(@user) %>
  </li>
  <li class="<%= 'active' if params[:tab] == 'comments' %>">
    <%= link_to "Comments (#{@comments.size})", user_path(@user, tab: 'comments') %>
  </li>
</ul>

<div class="row">
  <% if params[:tab].nil? %>
    <%= render 'posts/posts', posts: @posts %>
  <% else %>
    <%= render 'comments/comments', comments: @comments, show_post: true %>
  <% end %>
</div>